language: python
python:
- '3.7'
env:
 global:
  secure: QfXgoTOoSf7jj/sIo0Fk/5VsXV4da9Eb4kap9V9fKVjjp0MwRkXX/dh0RQzhP5dKFrzL0u8GXnCU12sX2Hwr8AR/Xqy1XVvFHP2kgpT7qxxczZIyyc2c2AdjBSOylVJC/WUwitdht/aWYIZeW5jBLpFWJ4FvY57RQ+ktQDTuTKPQq5eZ2i3fQMOtynAPVuaQWezxyf+zSuI4zwDzPenBer1DeXE/ZwdnPaczE691KlkxjdnjLn+fAmOUDuiWj85gjzEMbriguVH8z/uCbkt78pgiF5XU6D3tjD+DFRUvNiRKJ7rqTJwVCKCoJyggG2gWWA+ijl6TCO6fUJff63UG+Bxp76Jfj5sLdkKQYcMVNLuQEv0ZlL+rpsm19GdsXHO5hhZVaOkp1bIZXcgusiUr6HB6evex8r40cCq22WUV/hE+RzdkLM63Igubti5FvBTqFQrgt8dk48y8OuQokdmuGpbhtyeDT4zXz9+FoBl8BxyqXGy4JqdEOnlgJlXtNM3cAvpqR0wnK9sxM6/LWOdlTVBCBFqE5zPOm8SihHazugWd6zb8ryQEuESCi9bzCpba4DVhRjopzodc06bBNISuBQjZ5Y/Dv6oi6QKZf63JQYfQ/now6Ct32qVWGNA050Gc2/3elj+G2tGsTg2+kEhCygKenN4hUWFx3E8Vrgp1H2s=
before_install:
- echo $HOME
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda install -y -c anaconda python=3.7.6
- pip install tqdm
- conda config --set always_yes true --set changeps1 no
- conda update -q conda
- pip install -r requirements.txt
- pip install pytest pytest-cov
install:
- pip install .
before_script:
- conda install -y conda-build
- conda install -y anaconda-client
script:
- pytest test/test.py
after_success:
- echo "Tests completed successfully!"
after_failure:
- echo "Some test cases failed!"
deploy:
  provider: pypi
  user: __token__
  password:
  secure: OBc3A5ev15krWGKKApUjjE8pYNmEI3h3A/OXcc/KlnlW7MBksvrgzNPXbEhaUJ1/cYyzCAxJhOozFP8HO0Np80KkXZt26MCohhBTpDTcnzOm0JpE+wZBg+FQCRXNuELkwNj7B3mlrgZcXys3/qyjQ8CyqIg/4MAejIS/M7yPFgocJ+wdYlLPR4Q3GdnVoIv2X2GScPUFybpQ9PKxgZaB83amhXDKlphzFmxPoHIsak2fKZ7wbzFfWGRHL1pqk897fV+WSm+Oc4086NSYg+1pq5v45hCo3c5EGhdXf94Om554YDZd/YEq+EVzvHJ3noijjFFR1F51R9s5CBlObpV+WIF2xJRGm58oI3YkwSrNpLYKiNSUjqLgcLguMhwk+1VUCyCIrK2tOY2kAeXiBJgORl+MOigr66nJhGmNjdOVZ0ALputHHtz+4FqayFNR6fWvtnrS9O9NQtq9q5NZ4rQD90+ZOPcFrD87HujWL1aZGPfZt0IXlZQKTl5owV5JKKcMDIi7e8s9WwYX/IuG27yNLmbcb1I3K/nAS3B4Zg4ZCXqkbXBJekpPSVuYszFUlywzZmV8KqB5aYkBsur+n9FYkUuSGO7RlgwYPRnie6qSK1hXTWrZo0QsiDfhzwlw0rXiJxI2qF3/JDj39CJ1PeLvH5G9UnOJdINXKCBz7vgxoy4=
  on:
    tags: staging
    python: 3.7
  